ignoreGeneratedHeader = true

severity = "warning"

confidence = 0.8

errorCode = 1
warningCode = 1

enableAllRules = true

[rule.file-header]
    Disabled = true
[rule.max-public-structs]
    Disabled = true
[rule.line-length-limit]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.bare-return]
    Disabled = true
[rule.exported]
    Disabled = true
[rule.unhandled-error]
    Disabled = true
[rule.add-constant]
    Disabled = true
[rule.var-naming]
    Disabled = true

[rule.argument-limit]
    Arguments = [8]
[rule.cyclomatic]
    Arguments = [12]
[rule.cognitive-complexity]
    Arguments = [16]
[rule.function-result-limit]
    Arguments = [4]
